name: benchmark_gnn_slim
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.12
  - cudatoolkit==11.8.0
  - cudnn==8.9.7.29
  - pip
  - pip:
    - numpy==1.22.4
    - pandas==2.2.2
    - matplotlib==3.8.0
    - networkx==3.0
    - scikit-learn==1.3.0
    - scipy==1.11.1
    - scikit-image==0.21.0
    - GraphRicciCurvature==0.5.3
    - ninja==1.11.1.1
    - seaborn==0.13.2
    - medmnist==3.0.1

#torch==2.2.0+cu118 --index-url https://download.pytorch.org/whl/cu118
#torchvision==0.17.0+cu118 --index-url https://download.pytorch.org/whl/cu118
#torchaudio==2.2.0+cu118 --index-url https://download.pytorch.org/whl/cu118
#torchdata==0.7.1+cu118 --index-url https://download.pytorch.org/whl/cu118
# pip3 install torch==2.2.0+cu118 torchvision==0.17.0+cu118 torchaudio==2.2.0+cu118 torchdata==0.7.1 --index-url https://download.pytorch.org/whl/cu118
# pip install torch_scatter==2.1.2+pt22cu118 torch_sparse==0.6.18+pt22cu118 -f https://data.pyg.org/whl/torch-2.2.0+cu118.html
# pip install  dgl==2.3.0+cu118 -f https://data.dgl.ai/wheels/torch-2.2/cu118/repo.html
# pip install torch-sparse torch-sparse==0.6.15+cu118 --no-index -f https://data.pyg.org/whl/torch-1.6.0.html
# pip install torch-scatter torch-sparse==2.0.9+cu118 --no-index -f https://data.pyg.org/whl/torch-1.6.0.html
