#!/bin/bash

# Function to run the commands n times
run_commands() {
  local n=${1:-1} # Default to 1 if no parameter is specified

  for ((i = 0; i < n; i++)); do
    echo "Running iteration $((i + 1)) of $n"

    # Running commands for dataset PROTEINS with different models and parameters

    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure ricci_curvature
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure forman_curvature
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure random
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure degree_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure eigenvector_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure betweenness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure closeness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100 --num_batch 2000
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure ricci_curvature
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure forman_curvature
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure random
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure degree_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure eigenvector_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure betweenness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure closeness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure ricci_curvature
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure forman_curvature
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure random
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure degree_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure eigenvector_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure betweenness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure closeness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure ricci_curvature
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure forman_curvature
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure random
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure degree_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure eigenvector_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure betweenness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure closeness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100 --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS  --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 100  --max_communities 5 --hidden_channels 100 --num_batch 2000 --flow_control --flow_density 0.985 --linear
    python main_multilabel_classification_multigraph.py --dataset_name PROTEINS  --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 100  --max_communities 5 --hidden_channels 100 --num_batch 2000 --flow_control --flow_density 0.985

    # Running commands for dataset ENZYMES with different models and parameters

    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure ricci_curvature
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure forman_curvature
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure random
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure degree_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure eigenvector_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure betweenness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure closeness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure ricci_curvature
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure forman_curvature
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure random
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure degree_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure eigenvector_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure betweenness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure closeness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure ricci_curvature
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure forman_curvature
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure random
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure degree_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure eigenvector_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure betweenness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure closeness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure ricci_curvature
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure forman_curvature
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure random
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure degree_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure eigenvector_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure betweenness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure closeness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    
    python main_multilabel_classification_multigraph.py --dataset_name ENZYMES  --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --max_communities 5 --hidden_channels 100 --num_batch 2000 --flow_control --flow_density 0.985

    # Running commands for dataset MUTAG with different models and parameters

    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure ricci_curvature
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure forman_curvature
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure random
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure degree_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure eigenvector_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure betweenness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure closeness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure ricci_curvature
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure forman_curvature
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure random
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure degree_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure eigenvector_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure betweenness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure closeness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure ricci_curvature
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure forman_curvature
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure random
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure degree_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure eigenvector_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure betweenness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure closeness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure ricci_curvature
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure forman_curvature
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure random
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure degree_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure eigenvector_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure betweenness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure closeness_centrality
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    python main_multilabel_classification_multigraph.py --dataset_name MUTAG  --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --max_communities 5 --hidden_channels 100 --num_batch 2000 --flow_control --flow_density 0.83 --linear
    python main_multilabel_classification_multigraph.py --dataset_name MUTAG  --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --max_communities 5 --hidden_channels 100 --num_batch 2000 --flow_control --flow_density 0.83

    # Running commands for dataset COLLAB with different models and parameters

    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 500
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure ricci_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure forman_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure random
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure degree_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure eigenvector_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure betweenness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure closeness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GCN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure flow --aggregations_flow 3

    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 500
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure ricci_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure forman_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure random
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure degree_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure eigenvector_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure betweenness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure closeness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GIN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure flow --aggregations_flow 3

    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 500
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure ricci_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure forman_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure random
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure degree_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure eigenvector_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure betweenness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure closeness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type GAT --num_epoch 1000 --hidden_channels 100  --num_batch 500 --remove_edges 40 --topological_measure flow --aggregations_flow 3

    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --max_communities 5 --remove_edges 40 --topological_measure ricci_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --max_communities 5 --remove_edges 40 --topological_measure forman_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --max_communities 5 --remove_edges 40 --topological_measure random
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --max_communities 5 --remove_edges 40 --topological_measure degree_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --max_communities 5 --remove_edges 40 --topological_measure eigenvector_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --max_communities 5 --remove_edges 40 --topological_measure betweenness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --max_communities 5 --remove_edges 40 --topological_measure closeness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --hidden_channels 100  --num_batch 500 --max_communities 5 --remove_edges 40 --topological_measure flow --aggregations_flow 3

    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB  --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --max_communities 5 --hidden_channels 100 --num_batch 500 --flow_control --flow_density 0.98 --linear
    #python main_multilabel_classification_multigraph.py --dataset_name COLLAB  --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 1000 --max_communities 5 --hidden_channels 100 --num_batch 500 --flow_control --flow_density 0.98

    # Running commands for dataset IMDB-BINARY with different models and parameters

    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 2000
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure ricci_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure forman_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure random
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure degree_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure eigenvector_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure betweenness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure closeness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 2000
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure ricci_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure forman_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure random
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure degree_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure eigenvector_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure betweenness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure closeness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 2000
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure ricci_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure forman_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure random
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure degree_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure eigenvector_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure betweenness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure closeness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 2000 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure ricci_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure forman_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure random
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure degree_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure eigenvector_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure betweenness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure closeness_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --hidden_channels 100  --num_batch 2000 --max_communities 5 --remove_edges 5 --topological_measure flow --aggregations_flow 3

    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY  --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --max_communities 5 --hidden_channels 100 --num_batch 2000 --flow_control --flow_density 0.985 --linear
    #python main_multilabel_classification_multigraph.py --dataset_name IMDB-BINARY  --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --max_communities 5 --hidden_channels 100 --num_batch 2000 --flow_control --flow_density 0.985

    # Running commands for dataset REDDIT-BINARY with different models and parameters

    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 500
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure forman_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure random
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure degree_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure eigenvector_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GCN --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure flow --aggregations_flow 3

    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 500
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure forman_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure random
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure degree_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure eigenvector_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GIN --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure flow --aggregations_flow 3

    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 500
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure forman_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure random
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure degree_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure eigenvector_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type GAT --num_epoch 200 --hidden_channels 100  --num_batch 500 --remove_edges 10 --topological_measure flow --aggregations_flow 3

    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --hidden_channels 100  --num_batch 500 --max_communities 5 --remove_edges 15 --topological_measure forman_curvature
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --hidden_channels 100  --num_batch 500 --max_communities 5 --remove_edges 15 --topological_measure random
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --hidden_channels 100  --num_batch 500 --max_communities 5 --remove_edges 15 --topological_measure degree_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --hidden_channels 100  --num_batch 500 --max_communities 5 --remove_edges 15 --topological_measure eigenvector_centrality
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --hidden_channels 100  --num_batch 500 --max_communities 5 --remove_edges 15 --topological_measure flow --aggregations_flow 3

    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY  --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --max_communities 5 --hidden_channels 100 --num_batch 500 --flow_control --flow_density 0.98 --linear
    #python main_multilabel_classification_multigraph.py --dataset_name REDDIT-BINARY  --batch_norm --do_eval --print_result --model_type DeltaGNN --num_epoch 200 --max_communities 5 --hidden_channels 100 --num_batch 500 --flow_control --flow_density 0.98

  done
}

# Call the function with the argument passed to the script
run_commands "$1"